### ISSUE TITLE
I am getting CROS issue.

### ISSUE THREAD

**Issue by iamkdev** [gothinkster/rails-realworld-example-app#9]
Origin is not allowed by Access-Control-Allow-Origin.
When I try to access the api from the react app.
My rails-realworld-example-app running on port 3000
and react-redux-realworld-example-app  running on port 8000

**Comment by ahcarpenter** [comment]
try adding this code to` application.rb`:
```ruby
config.middleware.insert_before 3, 'Rack::Cors', debug: true, logger: (-> { Rails.logger }) do
  allow do
    origins ENV['CLIENT_ROOT_URL'] # in your case would be equal to http://localhost:8000

    resource '/api/*',
      headers: :any,
      methods: %i[get post delete put patch options head]
  end
end
```

**Comment by ahcarpenter** [comment]
@iamkdev try adding this code to` application.rb`:
```ruby
config.middleware.insert_before 3, 'Rack::Cors', debug: true, logger: (-> { Rails.logger }) do
  allow do
    origins ENV['CLIENT_ROOT_URL'] # in your case would be equal to http://localhost:8000

    resource '/api/*',
      headers: :any,
      methods: %i[get post delete put patch options head]
  end
end
```

**Comment by iamkdev** [comment]
Thanks @ahcarpenter. It works.

**Comment by ahcarpenter** [comment]
@iamkdev welcome!

**Comment by rajeevkannav** [comment]
![image](https://cloud.githubusercontent.com/assets/331827/26338814/d63d021c-3fa0-11e7-87c1-4fb38f4224cb.png)


Seems it's not fixed. I checkedout to Rails 5.1 Branch and It does'nt working.

**Comment by rajeevkannav** [comment]
As per above Comment origins `ENV['CLIENT_ROOT_URL']` reference which is now   
      
origins `Rails.application.secrets[:client_root_url]` in environment.

To make it working One should update `client_root_url` in secrets YAML depending upon React/FrontEnd App Port.

For Example, if my React/FrontEnd app Port is 4000 then `client_root_url` should be `http://localhost:4100`

Please consider this issue Closed (as it already). This comment is for Other People like me.

**Comment by iamkdev** [comment]
Thanks @rajeevkannav. Closing the issue as per your comment.

**Comment by hyperrjas** [comment]
I'm still having the same problem with localhost an angular4

![](https://preview.ibb.co/cybqTw/Screenshot_from_2017_10_02_12_59_12.png)

**environment.ts**
```
export const environment = {
  production: false,
  api_url: 'http://localhost:4201/api'
};

```
**secrets.yml**

```
shared:
  client_root_url: http://localhost:4201
```

**application.rb**

```
# frozen_string_literal: true

require_relative 'boot'

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Conduit
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.1
    config.api_only = true

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
    config.middleware.insert_before 0, Rack::Cors, debug: true, logger: (-> { Rails.logger }) do
      allow do
        origins Rails.application.secrets[:client_root_url]

        resource '/api/*',
                 headers: :any,
                 methods: %i[get post delete put patch options head]
      end
    end
  end
end

```
**rails server**
`rails s -p 4201`

![](https://preview.ibb.co/cL7Hab/Screenshot_from_2017_10_02_13_13_23.png)

Thank you!
